### ISSUE TITLE
Custom image loading placeholder

### ISSUE THREAD

**Issue by dgorczyca** [scaleflex/react-cloudimage-responsive#2]
Hi team,

Is it possible to tell the library to use a particular image / gif while the image is loading?
What would you recommend me to do in order to achieve that?
Currently I can see in your code cloudimageUrl and previewCloudimageUrl seem to use the same imgSrc.

**Comment by dzmitry-stramavus** [comment]
Hey @dgorczyca,

This feature is in todo list. It'll be available in a few days. Stay tuned)

**Comment by dzmitry-stramavus** [comment]
@dgorczyca, 

you can use **placeholderBackground** 

for example ([link to edit on CodeSandbox](https://codesandbox.io/s/jjq93749o3))
```
placeholderBackground: `url('https://scaleflex.ultrafast.io/https://scaleflex.airstore.io/filerobot/red-loader.gif') 50% 50% no-repeat`
```

you will see the following effect

![demo with custom spinner](https://scaleflex.ultrafast.io/https://scaleflex.api.airstore.io/v1/get/_/70120aa1-a18e-5f00-99b8-e39a13350000/add%20custom%20spinner.gif)

however, I used to slow my internet connection in order to see the spinner. The plugin uses Low Quality  Preview technic and uses smart cache. I think the best user experience will be to set just placeholder background color. By default it's set to #f4f4f4

```
placeholderBackground: '#f4f4f4'
```
